from pathlib import Path
import hashlib,json,sqlite3,time
R=Path(r'<LOCAL_DRIVE>/Sovereign_Entity_Network'); EV=R/'16_Test_Qualification/evidence'; Q=EV/'ENTITY_MILLION_ASSET_SCALE_CURRENT.json'; DB=Path(r'<LOCAL_DRIVE>/ENTITY_QUALIFICATION_SCALE\million_asset_v2\store\bulk_ingest.sqlite')
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def sealed(d):
 x=str(d.get('evidence_sha256') or ''); b=dict(d); b.pop('evidence_sha256',None)
 return bool(x and x==hashlib.sha256(json.dumps(b,sort_keys=True,separators=(',',':'),default=str).encode()).hexdigest())
d=json.loads(Q.read_text(encoding='utf-8'))
with sqlite3.connect(DB,timeout=120) as db: meta={k:v for k,v in db.execute('select k,v from meta')}
checks={'prior_full_qualification_seal':sealed(d),'prior_status_pass':d.get('status')=='PASS' and d.get('qualification_complete') is True,'prior_row_level_verified':d.get('verification',{}).get('pass') is True and d.get('verification',{}).get('row_level_verified') is True,'asset_total_1m':int(meta.get('asset_total',-1))==1_000_000,'event_total_3m':int(meta.get('event_total',-1))==3_000_000,'batch_head_match':meta.get('batch_head')==d.get('verification',{}).get('batch_head'),'database_size_match':DB.stat().st_size==d.get('database',{}).get('size_bytes'),'bulk_source_match':sha(R/'04_Entity_Registry/bulk_ingest/canonical_bulk_ingest.py')==d.get('source_sha256',{}).get('bulk_ingest'),'runner_source_match':sha(R/'16_Test_Qualification/performance/run_million_asset_scale.py')==d.get('source_sha256',{}).get('runner')}
p={'schema':'entity-million-scale-live-revalidation-v1','generated_at_ms':int(time.time()*1000),'status':'PASS' if all(checks.values()) else 'FAIL','qualification_complete':all(checks.values()),'state_root':str(DB.parent.parent),'database_path':str(DB),'checks':checks,'targets':d.get('targets'),'observed':d.get('observed'),'prior_evidence_sha256':d.get('evidence_sha256'),'prior_database_sha256':d.get('database',{}).get('sha256'),'live_meta':{'asset_total':int(meta['asset_total']),'event_total':int(meta['event_total']),'event_head':meta['event_head'],'batch_head':meta['batch_head']},'claim':'Live E: million-scale state remains bound to the previously completed full row-level qualification evidence.'}
b=json.dumps(p,sort_keys=True,separators=(',',':'),default=str).encode(); p['evidence_sha256']=hashlib.sha256(b).hexdigest(); out=EV/'ENTITY_MILLION_SCALE_REVALIDATION_CURRENT.json'; out.write_text(json.dumps(p,indent=2,sort_keys=True)+'\n',encoding='utf-8'); out.with_suffix('.json.sha256').write_text(sha(out)+'  '+out.name+'\n',encoding='utf-8')
print(json.dumps({'status':p['status'],'checks':checks,'evidence_sha256':p['evidence_sha256'],'output':str(out)},indent=2)); raise SystemExit(0 if p['status']=='PASS' else 2)