from pathlib import Path
import hashlib,json,time
ROOT=Path(r"<LOCAL_DRIVE>/Sovereign_Entity_Network"); EV=ROOT/"16_Test_Qualification"/"evidence"; OUT=EV/"ENTITY_POST_CHAOS_CLOSURE_CURRENT.json"
def load(p): return json.loads(Path(p).read_text(encoding="utf-8"))
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def sealed(d):
    x=str(d.get("evidence_sha256") or ""); b=dict(d); b.pop("evidence_sha256",None)
    return bool(x and x==hashlib.sha256(json.dumps(b,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest())
chaos_p=EV/"ENTITY_ULTIMATE_CHAOS_QUALIFICATION_CURRENT.json"; reg_p=EV/"ENTITY_REPOSITORY_REGRESSION_CURRENT.json"; e2e_p=EV/"ENTITY_FULL_E2E_QUALIFICATION_CURRENT.json"; genesis_p=EV/"ENTITY_GENESIS_PROOF_CURRENT.json"
rtm_p=ROOT/"16_Test_Qualification"/"traceability"/"MASTER_RTM.json"; gate_p=ROOT/"17_Release"/"manifests"/"ENTITY_10_10_RELEASE_GATE_CURRENT.json"
chaos,reg,e2e,genesis,rtm,gate=map(load,[chaos_p,reg_p,e2e_p,genesis_p,rtm_p,gate_p]); failed=[g for g in gate.get("gates",[]) if not g.get("pass")]
checks={"chaos_seal":sealed(chaos),"chaos_internal_pass":chaos.get("status")=="PASS" and chaos.get("scope_status")=="PASS_INTERNAL_SCOPE","regression_seal":sealed(reg),"regression_clean":int((reg.get("totals") or {}).get("failed",1))==0 and int((reg.get("totals") or {}).get("skipped",1))==0 and int((reg.get("totals") or {}).get("passed",0))>=422,"e2e_seal":sealed(e2e),"e2e_pass":e2e.get("status")=="PASS" and e2e.get("pytest_exit_code")==0,"genesis_seal":sealed(genesis),"genesis_pass":genesis.get("status")=="PASS","rtm_closed":rtm.get("full_internal_requirements_closed") is True and rtm.get("active_internal_unclosed_count")==0,"all_internal_release_gates":bool(gate.get("internal_gates_total")) and gate.get("internal_gates_passed")==gate.get("internal_gates_total"),"only_external_release_block":len(failed)==1 and failed[0].get("gate")=="sovereign_domain_external" and failed[0].get("external_only") is True}
status="PASS" if all(checks.values()) else "FAIL"
record={"schema":"entity-post-chaos-closure-v2","generated_at_ms":int(time.time()*1000),"status":status,"qualification_complete":status=="PASS","scope_status":"PASS_INTERNAL_SCOPE" if status=="PASS" else "FAIL_INTERNAL_SCOPE","checks":checks,"internal_engineering_blocker":None if status=="PASS" else "one_or_more_post_chaos_checks_failed","release_status":gate.get("status"),"release_score_percent":gate.get("score_percent"),"release_gates":{"passed":gate.get("gates_passed"),"total":gate.get("gates_total"),"internal_passed":gate.get("internal_gates_passed"),"internal_total":gate.get("internal_gates_total")},"external_release_blockers":[g.get("gate") for g in failed],"master_rtm":{"requirement_count":rtm.get("requirement_count"),"qualified":rtm.get("state_counts",{}).get("QUALIFIED"),"rtm_sha256":rtm.get("rtm_sha256"),"master_source_mirrored":rtm.get("master_source_mirrored"),"full_internal_requirements_closed":rtm.get("full_internal_requirements_closed")},"genesis":{"evidence_sha256":genesis.get("evidence_sha256"),"file_sha256":sha(genesis_p),"pytest":genesis.get("pytest")},"chaos":{"evidence_sha256":chaos.get("evidence_sha256"),"file_sha256":sha(chaos_p),"pytest_total":chaos.get("executed_pytest_total"),"generated_cases":chaos.get("generated_invariants",{}).get("generated_cases")},"post_chaos_regression":{"evidence_sha256":reg.get("evidence_sha256"),"file_sha256":sha(reg_p),"totals":reg.get("totals")},"post_chaos_full_e2e":{"evidence_sha256":e2e.get("evidence_sha256"),"file_sha256":sha(e2e_p)},"release_gate":{"gate_evidence_sha256":gate.get("gate_evidence_sha256"),"file_sha256":sha(gate_p)},"external_validation_pending":chaos.get("external_validation_pending",[]),"limitations":[],"claim":"RTM closure, Genesis Proof, Ultimate CHAOS and authoritative regression pass within the declared internally executable scope. Full external sovereign-domain release remains separately blocked."}
body=json.dumps(record,sort_keys=True,separators=(",",":"),default=str).encode(); record["evidence_sha256"]=hashlib.sha256(body).hexdigest()
OUT.write_text(json.dumps(record,indent=2,sort_keys=True)+"\n",encoding="utf-8"); OUT.with_suffix(".json.sha256").write_text(sha(OUT)+"  "+OUT.name+"\n",encoding="utf-8")
print(json.dumps({"status":status,"scope_status":record["scope_status"],"release_gates":record["release_gates"],"external_release_blockers":record["external_release_blockers"],"evidence_sha256":record["evidence_sha256"],"output":str(OUT)},indent=2)); raise SystemExit(0 if status=="PASS" else 2)
