from pathlib import Path
p=Path(r"<LOCAL_DRIVE>/Sovereign_Entity_Network\04_Entity_Registry\event_ledger\canonical_event_ledger.py")
s=p.read_text(encoding='utf-8')
start=s.index('    def verify(self)->dict:')
end=s.index('    def checkpoint(', start)
block='''    def verify(self)->dict:\n        """Streaming full-ledger verification with bounded memory and manifest caching."""\n        prior=ZERO_HASH; count=0; manifests={}\n        with self._connect() as db:\n            cur=db.execute("SELECT * FROM events ORDER BY sequence")\n            while True:\n                batch=cur.fetchmany(10000)\n                if not batch: break\n                for raw in batch:\n                    row=dict(raw)\n                    body={"schema":row["schema_version"],"event_id":row["event_id"],"event_type":row["event_type"],"actor_entity_id":row["actor_entity_id"],"subject_ids":json.loads(row["subject_ids_json"]),"object_ids":json.loads(row["object_ids_json"]),"payload_hash":row["payload_hash"],"evidence_origin":row["evidence_origin"],"confidence":row["confidence"],"timestamp_ms":row["timestamp_ms"],"prior_hash":row["prior_hash"]}\n                    sig=json.loads(row["signature_json"])\n                    if row.get("payload_sha256") not in {None,row["payload_hash"]}: return {"pass":False,"reason":"event_hash_failure","sequence":row["sequence"]}\n                    if row["prior_hash"]!=prior: return {"pass":False,"reason":"hash_chain_failure","sequence":row["sequence"]}\n                    if _sha({"body":body,"signature":sig})!=row["event_hash"]: return {"pass":False,"reason":"event_hash_failure","sequence":row["sequence"]}\n                    actor=row["actor_entity_id"]; manifest=manifests.get(actor)\n                    if manifest is None: manifest=self.identity.load_manifest(actor); manifests[actor]=manifest\n                    if not self.identity.verify_signature(manifest,body,sig): return {"pass":False,"reason":"signature_failure","sequence":row["sequence"]}\n                    prior=row["event_hash"]; count+=1\n            head=db.execute("SELECT v FROM meta WHERE k='head_hash'").fetchone()[0]\n        return {"pass":head==prior,"blocks":count,"head_hash":head,"streaming":True}\n'''
s=s[:start]+block+s[end:]
p.write_text(s,encoding='utf-8')
print('patched streaming verify')
