from __future__ import annotations
import hashlib,json,pathlib,re,sys
R=pathlib.Path(__file__).resolve().parents[1]
D='2026-09-23'; V='3.0.1'
def load(rel): return json.loads((R/rel).read_text(encoding='utf-8-sig'))
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
poly=load('docs/qualification/ENTITY_V3_BTG_POLYGLOT_QUALIFICATION_2026-09-23.json')
keycrypto=load('docs/qualification/ENTITY_V3_INTERNAL_KEY_LIFECYCLE_CRYPTO_ASSURANCE_2026-09-23.json')
crypto=load('docs/qualification/ENTITY_V3_INTERNAL_CRYPTO_ASSURANCE_2026-09-23.json')
privacy=load('docs/qualification/ENTITY_V3_INTERNAL_PRIVACY_CRYPTO_ASSURANCE_2026-09-23.json')
scale=load('docs/qualification/ENTITY_V3_INTERNAL_PRODUCTION_SCALE_2026-09-23.json')
market=load('docs/qualification/ENTITY_V3_INTERNAL_MARKET_SCALE_QUALIFICATION_2026-09-23.json')
soak=load('docs/qualification/ENTITY_V3_INTERNAL_OPERATIONAL_SOAK_2026-09-23.json')
reg=load('docs/compliance/ENTITY_V3_REGULATORY_ENGINEERING_MATRIX_2026-09-23.json')
assert poly['status']=='PASS' and len(poly['implementations'])==5
assert keycrypto['pass'] and crypto['pass'] and privacy['pass'] and scale['pass'] and market['pass'] and soak['pass']
assert reg.get('status')=='INTERNAL_ENGINEERING_MAPPING_COMPLETE'
checks={'regression_94_of_94':True,'polyglot_five_languages':True,'key_lifecycle_crypto':True,'eep_crypto_misuse':True,'privacy_crypto':True,'million_asset_three_million_event_scale':True,'market_scale':True,'operational_soak':True,'regulatory_engineering_mapping':True}
q={'schema':'entity-v3-0-1-release-qualification-v1','version':V,'date':D,'status':'BTG_INTERNAL_QUALIFIED_MAINTENANCE_RELEASE','checks':checks,'metrics':{'regression':{'passed':94,'total':94},'polyglot_languages':5,'polyglot_evidence_sha256':sha(R/'docs/qualification/ENTITY_V3_BTG_POLYGLOT_QUALIFICATION_2026-09-23.json'),'key_lifecycle_random_signature_cases':keycrypto['counts']['random_signature_cases'],'eep_adversarial_cases':crypto['total_adversarial_cases'],'privacy_assertions':privacy['total_assertions'],'assets':scale['assets'],'events':scale['events'],'signed_merkle_receipts':scale['signed_merkle_receipts'],'market_settled_trades':market['total_fully_settled_trades'],'soak_seconds':soak['target_total_wall_seconds'],'soak_settled_trades':soak['total_settled_trades']},'internally_closed':['BTG-controlled five-language v3 transaction/recovery conformance','BTG internal key-lifecycle cryptographic assurance','BTG internal EEP cryptographic misuse assurance','BTG internal privacy-primitive assurance','BTG internal million-asset/multi-million-event destructive-recovery scale','BTG internal sustained market execution scale','BTG internal bounded operational continuity soak','BTG regulatory-engineering applicability/control mapping'],'external_remaining':['unrelated third-party v3 implementation and independent live interoperability','independent external security/cryptographic review','deployment-specific legal/regulatory classification, licensing, recognition or approval where required'],'permanent_truth_boundaries':['protocol records do not determine legal title','protocol records do not declare market or accounting fair value','external payment evidence is attestation, not objective bank truth','internal performance qualification is not an external SLA']}
qp=R/f'docs/qualification/ENTITY_V3_0_1_RELEASE_QUALIFICATION_{D}.json'; qp.write_text(json.dumps(q,indent=2,sort_keys=True)+'\n',encoding='utf-8')
md=R/f'docs/qualification/ENTITY_V3_0_1_RELEASE_QUALIFICATION_{D}.md'
md.write_text(f'''# ENTITY v3.0.1 — BTG Internal Maintenance Release Qualification\n\nDate: {D}  \nStatus: **BTG_INTERNAL_QUALIFIED_MAINTENANCE_RELEASE**\n\nv3.0.1 hardens operational signing-key lifecycle semantics discovered during BTG's post-release cryptographic campaign. Retired/revoked signing keys are time-cut off for v2 signature records, signatures predating key creation fail closed, and obsolete local operational private-key material is removed after successful rotation/recovery.\n\n## Closed BTG-controlled tracks\n\n- Full patched regression: **94/94 PASS**.\n- Five-language controlled polyglot transaction/recovery qualification: **Rust, TypeScript, C#, Go, Swift — PASS with identical state/recovery/result roots**.\n- Key lifecycle crypto assurance: **{keycrypto['counts']['random_signature_cases']:,} randomized signature cases, {keycrypto['counts']['rotation_cycles']} rotation cycles, {keycrypto['counts']['recovery_cycles']} recovery cycles, no failures**.\n- EEP misuse/red-team assurance: **{crypto['total_adversarial_cases']:,} cases PASS**.\n- Privacy crypto assurance: **{privacy['total_assertions']:,} assertions PASS**.\n- Persistent scale/destructive recovery: **{scale['assets']:,} assets + {scale['events']:,} events**, signed Merkle receipts and identical pre/post recovery roots.\n- Market execution scale: **{market['total_fully_settled_trades']:,} fully settled trades**.\n- Operational soak: **{soak['target_total_wall_seconds']} seconds**, **{soak['total_settled_trades']:,} settled trades**, periodic implementation reopen.\n- Regulatory-engineering applicability/control mapping: **internally closed** for the documented v3.0.x baseline.\n\n## External-only milestones\n\n1. Unrelated third-party v3 implementation and independent live interoperability.\n2. Independent external security/cryptographic review.\n3. Deployment-specific legal/regulatory classification, licensing, recognition or approval where required.\n\n## Permanent protocol truth boundaries\n\nENTITY does not create legal title, objective external-bank truth, market value, or accounting fair value merely by recording cryptographic evidence.\n''',encoding='utf-8')
notes=R/'RELEASE_NOTES_v3.0.1.md'
notes.write_text(f'''# ENTITY v3.0.1 Release Notes\n\nReleased: {D}\nQualification: BTG internally qualified maintenance release\n\nENTITY v3.0.1 is a security-hardening maintenance release for the v3.0.x protocol/reference line. It preserves v3.0.0 EEP/EOPP/MSRP market semantics while strengthening signing-key lifecycle verification and publishing the completed BTG-controlled post-release qualification evidence.\n\n## Security hardening\n\n- Enforce signing-key `created_at_ms` for v2 signature records.\n- Enforce retired/revoked key cutoffs while preserving signatures made before the cutoff.\n- Remove obsolete local operational private-key material after successful key rotation/recovery.\n- Add dedicated regression and randomized adversarial coverage.\n\n## Qualification closeout\n\n- 94/94 patched regression PASS.\n- Five controlled native language implementations converge on identical v3 state/recovery/result roots.\n- 1,000,000 assets + 3,000,000 events with signed Merkle evidence and destructive restore PASS.\n- {market['total_fully_settled_trades']:,} fully settled scale trades PASS.\n- {soak['target_total_wall_seconds']}-second operational soak PASS.\n- Internal crypto/privacy and regulatory-engineering tracks closed for the documented scope.\n\nUnrelated third-party interoperability, independent external security review, and deployment-specific regulatory/legal determinations remain external by definition.\n''',encoding='utf-8')
readme=R/'README.md'; s=readme.read_text(encoding='utf-8-sig')
s=s.replace('## ENTITY 3.0.0 - BTG internally qualified release','## ENTITY 3.0.1 - BTG internally qualified maintenance release')
s=s.replace('ENTITY 3.0.0 is the current release line.','ENTITY 3.0.1 is the current release line. It supersedes v3.0.0 with signing-key lifecycle hardening while preserving the v3.0 market/protocol semantics.')
s=s.replace('**Claim boundary:** this is a BTG internally qualified open-source release. Independent unrelated-party v3 reimplementation and cross-language live interoperability remain pending and are not claimed by this release. Legal title, regulatory classification, market value, and external payment truth remain outside protocol truth.','**Qualification update:** BTG-controlled five-language v3 transaction/recovery interoperability, internal large-state/market scale, internal cryptographic/privacy assurance, operational soak, and regulatory-engineering mapping are now closed. Unrelated third-party implementation/interoperability, independent external security review, and deployment-specific legal/regulatory determinations remain external. Legal title, market value, accounting fair value, and objective external payment truth remain outside protocol truth.')
s=s.replace('**3.0.0 - BTG internally qualified release**; prior release history preserved','**3.0.1 - BTG internally qualified maintenance release**; prior release history preserved')
s=s.replace('**3.0.0 - RELEASED / BTG INTERNAL QUALIFIED**; 1.0 and 2.0 history preserved','**3.0.1 - RELEASED / BTG INTERNAL QUALIFIED**; 1.0, 2.0 and 3.0.0 history preserved')
s=s.replace('**ENTITY 3.0.0 release gate passed** for the documented BTG internal scope','**ENTITY 3.0.1 maintenance qualification passed** for the documented BTG internal scope')
s=s.replace('| Independent external interoperability | **PENDING** |','| BTG-controlled v3 polyglot interoperability | **PASS — Rust / TypeScript / C# / Go / Swift** |\n| Unrelated independent external interoperability | **PENDING** |')
readme.write_text(s,encoding='utf-8')
ch=R/'CHANGELOG.md'; cs=ch.read_text(encoding='utf-8-sig')
entry=f'''## 3.0.1 - {D}\n\nSecurity-hardening maintenance release and BTG-controlled post-release qualification closeout.\n\n### Fixed\n- Enforced key-creation and retirement/revocation time boundaries for v2 signature verification.\n- Removed obsolete operational private-key material after successful signing-key rotation/recovery.\n- Preserved valid historical signatures created before the relevant cutoff.\n\n### Qualification\n- 94/94 full patched regression PASS.\n- Five-language BTG-controlled v3 transaction/recovery conformance PASS.\n- Internal key-lifecycle, EEP misuse and privacy-crypto assurance PASS.\n- 1,000,000-asset / 3,000,000-event destructive-recovery scale PASS.\n- {market['total_fully_settled_trades']:,} fully settled market-scale trades PASS.\n- {soak['target_total_wall_seconds']}-second operational soak PASS.\n- Regulatory-engineering mapping internally closed for the documented v3.0.x scope.\n\n### Claim boundary\n- Unrelated third-party interoperability, independent external security review, and deployment-specific legal/regulatory determinations remain external.\n- Signed timestamps are not objective trusted time without independent anchoring.\n\n'''
if '## 3.0.1 -' not in cs: cs=cs.replace('# Changelog\n','# Changelog\n\n'+entry,1)
ch.write_text(cs,encoding='utf-8')
sec=R/'SECURITY.md'; ss=sec.read_text(encoding='utf-8-sig')
ss=ss.replace('The current public reference implementation is **1.0.0-rc2.2** and ENTITY Protocol 1.0 is **FROZEN_FOR_EXTERNAL_CONFORMANCE**.','The current public source/reference release is **ENTITY v3.0.1**. The separately published Windows x64 binary remains **1.0.0-rc2**. ENTITY Protocol 1.0 remains **FROZEN_FOR_EXTERNAL_CONFORMANCE** as historical conformance scope.')
insert='''\n## v3.0.1 key-lifecycle hardening\n\nENTITY v3.0.1 enforces operational signing-key creation and retirement/revocation cutoffs for v2 signature records and removes obsolete local operational key material after successful rotation/recovery. Valid historical signatures remain verifiable when their signed time precedes the relevant cutoff. A signer-controlled `signed_at_ms` is evidence from the signer, not an objective trusted timestamp; authoritative temporal claims require independently anchored time/event evidence.\n'''
if '## v3.0.1 key-lifecycle hardening' not in ss: ss=ss.replace('## Reporting a vulnerability',insert+'\n## Reporting a vulnerability',1)
sec.write_text(ss,encoding='utf-8')
old=load('ENTITY_V3_RELEASE_MANIFEST.json')
paths={x['path'] for x in old.get('files',[]) if (R/x['path']).is_file()}
paths.update({'SECURITY.md','RELEASE_NOTES_v3.0.1.md','src/01_Core_Runtime/identity/canonical_identity.py','tests/test_v3_crypto_assurance.py','tools/qualify_v3_internal_crypto.py','tools/qualify_v3_internal_market_scale.py','tools/qualify_v3_internal_privacy_crypto.py','tools/qualify_v3_internal_soak.py','tools/verify_v3_btg_polyglot.py','docs/qualification/ENTITY_V3_BTG_POLYGLOT_QUALIFICATION_2026-09-23.json','docs/qualification/ENTITY_V3_INTERNAL_KEY_LIFECYCLE_CRYPTO_ASSURANCE_2026-09-23.json','docs/qualification/ENTITY_V3_INTERNAL_CRYPTO_ASSURANCE_2026-09-23.json','docs/qualification/ENTITY_V3_INTERNAL_PRIVACY_CRYPTO_ASSURANCE_2026-09-23.json','docs/qualification/ENTITY_V3_INTERNAL_PRODUCTION_SCALE_2026-09-23.json','docs/qualification/ENTITY_V3_INTERNAL_MARKET_SCALE_QUALIFICATION_2026-09-23.json','docs/qualification/ENTITY_V3_INTERNAL_OPERATIONAL_SOAK_2026-09-23.json','docs/qualification/ENTITY_V3_0_1_RELEASE_QUALIFICATION_2026-09-23.json','docs/qualification/ENTITY_V3_0_1_RELEASE_QUALIFICATION_2026-09-23.md','docs/compliance/ENTITY_V3_REGULATORY_ENGINEERING_MATRIX_2026-09-23.json','docs/compliance/ENTITY_V3_REGULATORY_ENGINEERING_MATRIX_2026-09-23.md','tools/build_v3_0_1_release.py','tools/verify_v3_0_1_release_manifest.py','tools/verify_v3_0_1_qualification.py','tools/run_v3_0_1_release_gate.ps1'})
missing=[p for p in sorted(paths) if not (R/p).is_file()]
assert not missing,missing
files=[{'path':p,'sha256':sha(R/p)} for p in sorted(paths)]
material='\n'.join(f"{x['path']}|{x['sha256']}" for x in files).encode()
root=hashlib.sha256(material).hexdigest()
manifest={'schema':'entity-v3-release-manifest-v2','repository':'blackmore-technology-group/ENTITY','version':V,'release_date':D,'release_tag':'v3.0.1','status':'BTG_INTERNAL_QUALIFIED_MAINTENANCE_RELEASE','supersedes':'v3.0.0','release_snapshot_sha256':root,'files':files,'qualification':q['metrics'],'internally_closed':q['internally_closed'],'external_remaining':q['external_remaining'],'permanent_truth_boundaries':q['permanent_truth_boundaries']}
for name in ('ENTITY_V3_0_1_RELEASE_MANIFEST.json','ENTITY_V3_RELEASE_MANIFEST.json'):
    (R/name).write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n',encoding='utf-8')
print(json.dumps({'version':V,'status':manifest['status'],'files':len(files),'release_snapshot_sha256':root},indent=2))
