from pathlib import Path
p=Path(r"<LOCAL_DRIVE>/Sovereign_Entity_Network\04_Entity_Registry\ownership_graphs\canonical_rights_claims.py")
s=p.read_text(encoding="utf-8")
old='RIGHT_TYPES={"AUTHOR","CREATOR","COPYRIGHT_CLAIMANT","COPYRIGHT_OWNER","DATA_CONTROLLER","DATA_CUSTODIAN","PERSONAL_DATA_SUBJECT","DEPICTED_PERSON","TRADEMARK_INTEREST","PATENT_INTEREST","CONFIDENTIALITY_INTEREST","LICENSEE","LICENSOR","LICENSING_AUTHORITY","ROYALTY_PARTICIPANT","COLLECTIVE_CONTROLLER","EMPLOYER_INTEREST","EMPLOYEE_INTEREST","GUARDIAN","ESTATE_INTEREST","PLATFORM_LICENSE_HOLDER","AGENT"}'
new='RIGHT_TYPES={"AUTHOR","CREATOR","COPYRIGHT_CLAIMANT","COPYRIGHT_OWNER","CONTROLLER","CUSTODIAN","DATA_CONTROLLER","DATA_CUSTODIAN","PERSONAL_DATA_SUBJECT","DEPICTED_PERSON","TRADEMARK_INTEREST","PATENT_INTEREST","CONFIDENTIALITY_INTEREST","LICENSEE","LICENSOR","LICENSING_AUTHORITY","ROYALTY_PARTICIPANT","EMPLOYEE_EMPLOYER_INTEREST","EMPLOYER_INTEREST","EMPLOYEE_INTEREST","COLLECTIVE_OWNER","COLLECTIVE_CONTROLLER","GUARDIAN","ESTATE","ESTATE_INTEREST","PLATFORM_LICENSE_HOLDER","AUTHORIZED_AGENT","AGENT"}'
if old not in s: raise SystemExit("right types target not found")
s=s.replace(old,new)
s=s.replace('EVIDENCE_ORIGINS={','ONTOLOGY_VERSION="entity-rights-ontology-v1"\nEVIDENCE_ORIGINS={')
p.write_text(s,encoding="utf-8")
